### ISSUE TITLE
Can you add please popup for killing buffers? 

### ISSUE THREAD

**Issue by welf** [kostafey/popup-switcher#7]
I use your plugin as replacement for standard commands for finding files, switching buffers and opening recent files. But there is similar pattern for killing buffer(s). Can you please add popup for this function too? 

I see that this popup should kill buffer and close after pressing `RET` and kill buffer, but not close (until there are no available buffers) when desired buffer is selected and I press `k` or `d` to be able to kill more than one buffer invoking popup only once.

**Comment by kostafey** [comment]
Since `isearch` is enabled by defaut for any popup menu here, you can't use any `self-insert-command`, like `k` or `d`. I can't see any reason to add special case here. Moreover, we need just list of buffers, so we can use `psw-switch-buffer` function and add `C-d` key to it's key-map to kill selected buffer. Is such behaviour suitable for you?

**Comment by welf** [comment]
Yes, of course. It is even better if you could be able to switch to another buffer or kill buffers using single popup menu.

**Comment by kostafey** [comment]
Done in `0.2.10`. BTW, I can't correctly persist menu when you killing current buffer, so in this case, menu will be closed.

**Comment by welf** [comment]
Thank you!
